spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: 123456
    url: jdbc:mysql://175.24.51.62:3306/vhr?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
  rabbitmq:
    username: admin
    password: admin
    host: 175.24.51.62
    publisher-confirms: true
    publisher-returns: true
  redis:
    host: 175.24.51.62
    database: 0
    port: 6379
    password: ye@h0
  cache:
    cache-names: menus_cache
server:
  port: 8081
  compression:
    enabled: true
fastdfs:
  nginx:
    host: http://175.24.51.62/